<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_star_border_baris_8</name>
   <tag></tag>
   <elementGuidId>02444a7c-3143-4d36-b6ee-50543a284221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-1-2']/div/table/tbody/tr[8]/td[3]/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;SPI Wilayah Aceh KANTOR PUSAT&quot;i] >> mat-icon >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>4c8dcd6b-8c86-47b9-8d04-b03b6b98210b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c953f6d2-76c3-4692-b190-73f859bc101c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>e6cee780-6f64-4103-8649-cb2449016dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f300f1c8-5f05-4853-8f7e-8140745e692d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>star_border</value>
      <webElementGuid>9626d78e-5909-4a94-89a6-36b2b34bf192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-2&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c231-62 ng-trigger ng-trigger-translateTab&quot;]/table[@class=&quot;mat-table cdk-table mat-elevation-z8 ng-star-inserted&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-staricon mat-column-staricon ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>dc766286-b05a-4edd-9e1a-933b50fe9c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-2']/div/table/tbody/tr[8]/td[3]/mat-icon</value>
      <webElementGuid>fcdc4026-9a2e-469f-a8a9-052863f71d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KANTOR PUSAT'])[8]/following::mat-icon[1]</value>
      <webElementGuid>2de7972b-f4e6-4b18-a003-8bbf0582d34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPI Wilayah Aceh'])[1]/following::mat-icon[1]</value>
      <webElementGuid>3c5db696-aa95-49a3-9f7f-cec52177083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AK3L ACEH'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>6d6379d3-e709-4de8-a0c8-10399e7ecd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KANTOR PUSAT'])[9]/preceding::mat-icon[2]</value>
      <webElementGuid>8ae9ec1b-d17b-4912-999f-d19362cfc8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/mat-icon</value>
      <webElementGuid>e727b089-a0de-463a-95eb-ccf38fd0d9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'star_border' or . = 'star_border')]</value>
      <webElementGuid>ce15ee01-6e9c-40b2-a58f-397c6dbacccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
