<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kepada</name>
   <tag></tag>
   <elementGuidId>662ce42d-d252-46d7-94be-949db2f63794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.link-addressbook</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-2']/div/table/tr[3]/td/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kepada&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b27df07d-b1ec-4d28-b3b9-3af0f9ffcbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-addressbook</value>
      <webElementGuid>0a25d0d9-9b0c-41fe-8444-6aeef5fe6718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kepada</value>
      <webElementGuid>5f07ab3a-7773-4998-990f-c8004cb8bb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-2&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c231-32 ng-trigger ng-trigger-translateTab&quot;]/table[@class=&quot;table-dialog ng-star-inserted&quot;]/tr[3]/td[@class=&quot;width-menu ng-star-inserted&quot;]/p[@class=&quot;link-addressbook&quot;]</value>
      <webElementGuid>d524fa6b-8bd1-4536-8fd0-77ff5bf3ce37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-2']/div/table/tr[3]/td/p</value>
      <webElementGuid>afe7806b-b4a2-48f5-b1d2-b580adb79525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilan Kepada'])[1]/preceding::p[2]</value>
      <webElementGuid>f24332a4-8f6c-444d-96cb-ec1e94a07d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilan Tembusan'])[1]/preceding::p[5]</value>
      <webElementGuid>aa3c40fc-8da9-4ff5-96e5-3584e266825e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kepada']/parent::*</value>
      <webElementGuid>50f952da-a337-4150-bbba-3e64a2221804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/p</value>
      <webElementGuid>1f413d6a-ba6f-46d9-bb08-632eeef7bb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kepada' or . = 'Kepada')]</value>
      <webElementGuid>361034c5-5e6d-4292-8313-871f3c49ab5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
