<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Dari_mat-datepicker-toggle-default-icon_04302c</name>
   <tag></tag>
   <elementGuidId>7fe1a075-452b-471a-9140-92a6cb90ac49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.mat-datepicker-toggle-default-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>mat-form-field >> internal:has-text=&quot;Dari&quot;i >> internal:label=&quot;Open calendar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>03abf4e9-1bdf-40a5-9b4e-66dfdbc2ede6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>de287954-8962-4c87-aa10-f2d32daeb82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>9b2b1d03-acc2-4f04-a780-ebd79774b020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>679f8e2e-73ee-40ad-82c8-9502a6e0e16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>1a158e86-f8d1-42df-9639-892f444b8be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37b84ca1-69ba-4642-8a80-d8d643ca923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-datepicker-toggle-default-icon ng-star-inserted</value>
      <webElementGuid>ef2312fd-48e8-4996-80bc-b42ade248335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranslate&quot;]/body[1]/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container container&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content ng-star-inserted&quot;]/div[@class=&quot;sidenav-content&quot;]/app-smasuk-list[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar toolbar-custom mat-toolbar-multiple-rows&quot;]/mat-toolbar-row[@class=&quot;mat-toolbar-row toolbar-row-custom&quot;]/div[1]/mat-form-field[@class=&quot;mat-form-field custom-form-field-date ng-tns-c94-27 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-should-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c94-27&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c94-27&quot;]/div[@class=&quot;mat-form-field-suffix ng-tns-c94-27 ng-star-inserted&quot;]/mat-datepicker-toggle[@class=&quot;mat-datepicker-toggle ng-tns-c94-27&quot;]/button[@class=&quot;mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/svg[@class=&quot;mat-datepicker-toggle-default-icon ng-star-inserted&quot;]</value>
      <webElementGuid>c38a4b0d-7c94-4483-aa8c-5f0558e1db1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0b5d8b57-678d-4f7f-a803-4461ff84e1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>31f9c958-231e-454b-b404-b7e85aab5f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>acb934f0-c0d9-428b-96d2-9761c78243a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hingga'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>3de0f294-a8b4-4d18-978a-0e044b8b5ac8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
